package com.fredroid.mathsymbol;

/**
 * Created by jackttc on 10/8/17.
 */
class  MetaItem {
    final static int BASIC = 1;
    final static int GEOMETRY = 2;
    final static int ALGEBRA = 3;
    final static int PROBABILITY = 4;
    final static int SET = 5;
    final static int LOGIC = 6;
    final static int CALCULUS = 7;


    static String[][] mathBasic = new String[][]{
            {"=", "equals sign"},
            {"≠", "not equal sign"},
            {"≈", "approximately equal"},
            {">", "greater than"},
            {"<", "less than"},
            {"≥", "greater than or equal to"},
            {"≤", "less than or equal to"},
            {"( )", "parentheses"},
            {"[ ]", "brackets"},
            {"+", "addition"},
            {"-", "minus or subtraction"},
            {"±", "plus and minus"},
            {"*", "asterisk,multiplication"},
            {"×", "times,multiplication"},
            {"⋅", "multiplication dot"},
            {"÷", "division sign"},
            {"/", "division slash"},
            {"—", "division,fraction"},
            {"mod", "modulo"},
            {".", "decimal point, decimal separator"},
            {"fig", "power"},
            {"a^b", "caret"},
            {"fig", "square root"},
            {"fig", "cube root"},
            {"fig", "nth root"},
            {"%", "percent"},
            {"‰", "per-mille"},
            {"ppm", "per-million"},
            {"ppb", "per-billion"},
            {"ppt", "per-trillion"},
            };
    static String[][] mathGeometry = new String[][]{
            {"∠", "angle"},
            {"fig","measured angle"},
            {"fig","spherical angle"},
            {"∟", "right angle"},
            {"°", "degree"},
            {"deg", "degree"},
            {"′", "prime, arcminute"},
            {"\"", "double prime, arcsecond"},
            {"fig", "infinite line"},
            {"fig", "line from point A to point B"},
            {"fig", "arc from point A to point B"},
            {"⊥", "perpendicular,perpendicular lines"},
            {"||", "parallel line"},
            {"≅", "congruent to, equivalence of geometric shapes and size"},
            {"~", "similarity, same shapes, not same size"},
            {"Δ", "triangle, triangle shape"},
            {"|x-y|", "distance between points x and y"},
            {"rad", "radians"},
            {"*", "asterisk"}};
    static String[][] mathAlgebra = new String[][]{
            {"≡", "equivalence,identical to"},
            {"≜", "equal by definition"},
            {":=", "equal by definition"},
            {"~", "approximately equal"},
            {"≈", "approximately equal"},
            {"∝", "proportional to"},
            {"∞", "infinity"},
            {"≪", "much less than"},
            {"≫", "much greater than"},
            {"( )", "parentheses"},
            {"[ ]", "brackets"},
            {"{ }", "braces"},
            {"⌊x⌋", "floor brackets, rounds number to lower integer"},
            {"⌈x⌉", "ceiling brackets, rounds number to upper integer"},
            {"!", "exclamation mark, factorial"},
            {"|x|", "single vertical bar,absolute value"},
            {"f(x)", "function of x"},
            {"fig", "function composition"},
            {"∆", "delta, change or difference"},
            {"∑", "sigma, summation"},
            {"∑∑", "double sigma, double summation"},
            {"∏", "pi, product of all values"},
            {"e", "e constant, 2.718281828..."},
            {"γ", "Euler constant, 0.527721566"},
            {"φ", "golden ration constant"},
            {"π", "pi constant, 3.1415926"}};
    static String[][] mathProbability = new String[][]{
            {"P(A)", "probability of event A"},
            {"P(A∩B)", "probability of events A and B"},
            {"P(A∪B)", "probability of events A or B"},
            {"P(A|B)", "probability of event A given event B occured"},
            {"f(x)", "probability density function(pdf)"},
            {"F(x)", "cumulative distribution function(cdf)"},
            {"μ", "mean of population values"},
            {"E(X)", "expected value of random variable X"},
            {"E(X|Y)", "expected value of random variable X given Y"},
            {"var(X)", "variance of random variable X"},
            {"fig", "variance of population values"},
            {"std(X)", "standard deviation of random variable X"},
            {"fig", "standard deviation value of random variable X"},
            {"fig", "middle value of random variable X"},
            {"cov(X,Y)", "covariance of random variables X and Y"},
            {"corr(X,Y)", "correlation of random variables X an Y"},
            {"fig", "correlation of random variables X and Y"},
            {"∑", "summation"},
            {"∑∑", "double summation"},
            {"Mo", "value that occurs most frequently in population"},
            {"MR", "Mid-range"},
            {"Md", "sample median"},
            {"Q1", "lower quartile or first quartile"},
            {"Q2", "median quartile or second quartile"},
            {"Q3", "upper quartile or third quartile"},
            {"fig", "sample mean"},
            {"fig", "sample variance"},
            {"fig", "standard score"},
            {"X~", "distribution of X,X~N(0,3)"},
            {"fig", "normal distribution"},
            {"U(a,b)", "normal distribution"},
            {"exp(λ)", "exponential distribution"},
            {"gamma(c, λ)", "gamma distribution"},
            {"fig", "chi square distribution"},
            {"fig", "F distribution"},
            {"Bin(n,p)", "binomial distribution"},
            {"Poisson(λ)", "Poisson distribution"},
            {"Geom(p)", "geometric distribution"},
            {"HG(N,K,n)", "hyper-geometric distribution"},
            {"Bern(p)", "Bernoulli distribution"},
            };
    static String[][] mathSet = new String[][]{
            {"{ }", "set"},
            {"A ∩ B", "intersection"},
            {"A ∪ B", "union"},
            {"A ⊆ B", "subset"},
            {"A ⊂ B", "proper subset or strict subset"},
            {"A ⊄ B", "not subset"},
            {"A ⊇ B", "superset"},
            {"A ⊃ B", "proper superset or superset"},
            {"A ⊅ B", "not superset"},
            {"fig", "power set"},
            {"fig", "complement"},
            {"A\\B", "relative complement"},
            {"A-B", "relative complement"},
            {"A∆B", "symmetric difference"},
            {"a∈A", "element of"},
            {"x∉A", "not element of"},
            {"(a,b)","ordered pair"},
            {"A×B", "cartesian product"},
            {"|A|", "cardinality, the number of elements of set A"},
            {"fig","aleph null means infinite cardinality of natural numbers set"},
            {"fig","aleph one means cardinality of countable ordinal number set"},
            {"Ø", "empty set"},
            {"fig", "whole numbers set"},
            {"fig", "whole numbers set without zero"},
            {"fig", "integer numbers set"},
            {"fig", "rational numbers set"},
            {"fig", "real numbers set"},
            {"fig", "complex numbers set"},
};
    static String[][] mathLogic = new String[][]{
            {"⋅", "and"},
            {"^", "caret/circumflex, and"},
            {"&", "ampersand, and"},
            {"+", "plus,or"},
            {"V", "reversed caret, or"},
            {"|", "vertical line, or"},
            {"x'", "single quote, not-negation"},
            {"fig", "not negation"},
            {"¬", "not, not negation"},
            {"!", "exclamation mark, not negation"},
            {"⊕", "circled plus/oplus/exclusive,xor"},
            {"~", "tilde,negation"},
            {"⇒", "implies"},
            {"⇔", "equivalent, if and only if(iff)"},
            {"⇔", "equivalent, if and only if(iff)"},
            {"∀", "for all"},
            {"∃", "there exists"},
            {"∄", "there does not exists"},
            {"∴", "therefore"},
            {"∵", "because or since"},
            };
    static String[][] mathCalculus = new String[][]{
            {"fig", "limit"},
            {"ε", "epsilon"},
            {"e", "e constant, 2.718281828..."},
            {"y'", "derivative"},
            {"y\"", "second derivative"},
            {"fig", "nth derivative"},
            {"fig", "derivative"},
            {"fig", "second derivative"},
            {"fig", "nth derivative "},
            {"fig", "time derivative"},
            {"fig", "time second derivative"},
            {"fig", "partial derivative"},
            {"∫", "integral"},
            {"∫∫", "double integral"},
            {"∫∫∫", "triple integral"},
            {"∮", "closed contour/line integral"},
            {"∯", "closed surface integral"},
            {"∰", "closed volume integral"},
            {"[a,b]", "closed interval"},
            {"(a,b)", "open interval"},
            {"i", "imaginary unit"},
            {"fig", "complex conjugate"},
            {"fig", "complex conjugate "},
            {"∇", "nable/del"},
            {"fig", "vector"},
            {"fig", "unit vector"},
            {"x*y", "convolution"},
            {"δ", "delta function"},
            {"∞", "lemniscate,infinity symbol"},


};



}